spring:
  application:
    name: erp
  datasource:
    url: jdbc:postgresql://localhost:5432/erp
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update # update schema tanpa hapus data lama
    show-sql: true

server:
  port: 8080

camunda:
  bpm:
    auto-deployment-enabled: true

spring.devtools:
  restart:
    enabled: true # otomatis restart saat ada perubahan kode
  livereload:
    enabled: true # reload browser jika pakai web
